[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Adamas"
version = "0.0.1"

dependencies = [
    "torch==2.5.0",
    "transformers==4.45.2",
    "accelerate==1.0.1",
    "sentencepiece==0.2.0",
    "datasets==3.0.1",
    "jieba==0.42.1",
    "fuzzywuzzy==0.18.0",
    "rouge==1.0.1",
    "pandas==2.2.3",
    "fschat==0.2.36",
    "numpy==2.1.2",
    "tqdm",
    "wonderwords",
    "nltk",
    "PyYAML",
    "scipy",
    "html2text",
    "beautifulsoup4"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["adamas*", "evaluation*"]
